name: Demo CI/CD

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Show Files
        run: ls

      - name: Show Current Directory
        run: pwd

      - name: Print HTML File
        run: cat index.html

      - name: Success Message
        run: echo "Pipeline Executed Successfully"